CREATE SCHEMA final_project_db;
USE final_project_db;

CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(45) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    USER_PASSWORD VARCHAR(200) NOT NULL
);

CREATE TABLE ANIMES(
	ANIME_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(60) NOT NULL,
    SINOPSIS VARCHAR(1024) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    EPISODES SMALLINT NOT NULL
);
